### PR TITLE
Update table layout and dash colors

### PR DESCRIPTION
**Pull request by AlenkaF**

### CODE REVIEW

**Comment by AlenkaF** [comment]
More updates to the dash (tables, colours). Current look:

Screenshot 2024-07-17 at 18 28 36

Screenshot 2024-07-17 at 18 28 27

Screenshot 2024-07-17 at 18 28 55

I need to fix the plots in summary and we could pick some nice colours for that also (I am using those from https://arrow.apache.org/visual_identity/). What do you think @thisisnic ?

**Comment by AlenkaF** [comment]
> I love the black and white theme, this is really great!

Cool!

> I think the highlighting of new contributors rows should be paler, and you probably noticed this already, but the icons disappeared from the summary boxes at the top.

I will use a paler version of the orange.
As for the icons in value boxes, I have removed them when testing the layout on my screens. As the hight of the dash is fixed the boxes were always half showing on my screen, for example:

Screenshot 2024-07-18 at 12 38 51

I am also trying to add the "Update time" to the footer (if it exists for the dashboards) so that we have more space for the boxes. No luck yet though.

**Comment by thisisnic** [comment]
I don't think the footer thing is possible: https://forum.posit.co/t/r-expressions-in-quarto-yaml-header/171482/3?u=thisisnic

**Comment by AlenkaF** [comment]
What do you think about having the date in the title?

Screenshot 2024-07-18 at 15 24 03

**Comment by thisisnic** [comment]
> What do you think about having the date in the title?
> Screenshot 2024-07-18 at 15 24 03

Looks good to me!

**Comment by thisisnic** [comment]
Awesome! How did you do that?

**Comment by AlenkaF** [comment]
Latest look locally:

Screenshot 2024-07-19 at 20 37 52

**Comment by AlenkaF** [comment]
I will merge this PR as I like the current look:

Screenshot 2024-07-20 at 19 06 19

Feel free to change the layout while I am off @thisisnic.

**Comment by AlenkaF** [comment]
PS: I will try to optimise the code when I get back as I think there are nicer ways of preparing the data in Python.

**Pull request merged**
